export const DOCTORS_PAGE_DOCTORS = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Jenkins',
    specialty: 'Senior Cardiologist',
    clinic: 'Downtown Medical Center',
    location: 'Downtown Medical Center',
    rating: 4.9,
    reviewsCount: 213,
    nextAvailable: 'Today, 2:30 PM',
    availableDate: '2026-07-25',
    image: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&q=80&w=600',
    modes: ['Telehealth', 'In-Person'],
  },
  {
    id: 'doc-2',
    name: 'Dr. Marcus Chen',
    specialty: 'Neurologist',
    clinic: 'Westside Health Clinic',
    location: 'Westside Health Clinic',
    rating: 4.7,
    reviewsCount: 156,
    nextAvailable: 'Tomorrow, 09:15 AM',
    availableDate: '2026-07-26',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600',
    modes: ['In-Person Only'],
  },
  {
    id: 'doc-3',
    name: 'Dr. Emily Thorne',
    specialty: 'Orthopedic Surgeon',
    clinic: 'North Hospital',
    location: 'North Hospital',
    rating: 5.0,
    reviewsCount: 89,
    nextAvailable: 'Wed, Nov 15',
    availableDate: '2026-07-30',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=600',
    modes: ['Telehealth'],
  },
];
