export const MOCK_APPOINTMENTS = [
  {
    id: 'MS-8824',
    status: 'Upcoming',
    day: 'Today',
    time: '14:30 PM (IST)',
    doctorName: 'Dr. Sarah Jenkins',
    specialty: 'Cardiology Specialist',
    consultationType: 'Telehealth Consultation',
    patientsAhead: 3,
    doctorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    hasBadge: true,
  },
  {
    id: 'MS-9012',
    status: 'Scheduled',
    day: 'Tomorrow',
    time: '10:00 AM (IST)',
    doctorName: 'Dr. Alan Turing',
    specialty: 'Neurology',
    consultationType: 'In-Person Visit',
    patientsAhead: null,
    doctorImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    hasBadge: false,
  },
  {
    id: 'MS-9401',
    status: 'Scheduled',
    day: 'Jul 28',
    time: '11:15 AM (IST)',
    doctorName: 'Dr. Emily Carter',
    specialty: 'Dermatology',
    consultationType: 'Telehealth Consultation',
    patientsAhead: null,
    doctorImage: 'https://images.unsplash.com/photo-1594824813566-88855ce783d1?auto=format&fit=crop&q=80&w=300',
    hasBadge: false,
  },
];